# Site settings
title: Significunt
email: annharter @ gmail . com
description: > # this means to ignore newlines until "baseurl:"
  I'm actually very nice. Pleasure to meet you, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.significunt.com" # the base hostname & protocol for your site
twitter_username: anyharder
github_username:  theaisforannie

# Build settings
markdown: kramdown
